### ISSUE TITLE
Can node-Tor be used to fully replace tor daemon to publish services?

### ISSUE THREAD

**Issue by RobertoMalatesta** [Ayms/node-Tor#11]
Hi @Ayms , and thanks for this beautiful and massive project!

I have one (dumb) question:
Can node-Tor fully replace the tor service to publish .onion sites?

Thanks in advance and keep rocking.

--Rob

**Comment by Ayms** [comment]
Thanks but I think that the answer is no, not difficult but the hidden services features are not implemented (and as stated in other issues the full code is still not available until this project gets financed a bit)

**Comment by RobertoMalatesta** [comment]
Thanks for the prompt response.
On the Financing part: maybe the correct model is to get sponsorship by Tor Project itself or NodeJS Foundation.
I see a value for them.

--R

**Comment by Ayms** [comment]
Maybe, still trying... the Tor project is very well aware of that project and never made a single move (like their sponsors) to help/support this, which did not prevent them from asking different things to investigate some stuff they could not understand, and I replied each time

**Comment by RobertoMalatesta** [comment]
> the Tor [...] each time

I like to read terse sentences that target a cluster of issues in few words :smiley:
