### ISSUE TITLE
node-Tor/build/Release/crypto.node: wrong ELF class: ELFCLASS64

### ISSUE THREAD

**Issue by gvsurenderreddy** [Ayms/node-Tor#6]
Hello i'm using 32 bit .Is it possible to send build with 32 as well

**Comment by Ayms** [comment]
Hi, not sure to what part of the code you are referring to, as stated in the repo only the initial commit (not maintained) is under a MIT license for now, not the full version, but it can be used to build something based on the Tor protocol.

So unfortunately I am afraid that you are on your own to solve the issues that your project/conf can raise...
